language: cpp
dist: bionic
compiler: gcc

install:
  - sudo apt-get update -q
  # GCC 9
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  # magic_enum
  - my_github=${PWD##*/}  
  - cd ..
  - git clone https://github.com/Neargye/magic_enum.git
  - cd $my_github

script: 
  - qmake
  - make --silent
  - ./travis_qmake_gcc_cpp17_magic_enum
