language: cpp
dist: bionic
compiler: gcc

install:
  # magic_enum
  - my_github=${PWD##*/}  
  - cd ..
  - git clone https://github.com/Neargye/magic_enum.git
  - cd $my_github

script: 
  - qmake
  - make --silent
  - ./travis_qmake_gcc_cpp17_magic_enum
